#!/bin/sh
#PBS -N CUBLAS_sgemm_P
#PBS -l nodes=1:ppn=1
#PBS -l walltime=7:29:00
#PBS -j oe
#PBS -q lincoln
#PBS -V

/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 100
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 120
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 140
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 160
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 180
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 200
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 220
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 240
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 260
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 280
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 300
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 320
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 340
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 360
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 380
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 400
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 500
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 600
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 700
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 800
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 900
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 1000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 1500
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 2000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 2500
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 3000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 4000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 5000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 6000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 7000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 8000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 9000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 10000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 11000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 12000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 13000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 14000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 15000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 16000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 17000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 18000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 19000
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 20000
