#!/bin/sh
#PBS -N CUBLAS_sgemm_P
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:29:00
#PBS -j oe
#PBS -q lincoln_debug
#PBS -V

/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 1
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 10
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 100
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 200
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 300
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 400
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 500
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 600
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 700
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 800
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 900
echo ""
echo "======================================"
echo ""
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/CUBLAS_sgemm_P.x 1 1000
