#!/bin/sh
#PBS -N GPU_GEMM_TEST
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:25:00
#PBS -j oe

echo "Using serial BLAS"
/homes/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_S.x 1
/homes/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_S.x 2
echo "Using threaded BLAS"
/homes/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 1
/homes/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 2
