#!/bin/sh
#PBS -N ga_cpu_sgemm
#PBS -l nodes=8:ppn=8
#PBS -l walltime=0:30:00

cd $PBS_O_WORKDIR

export MPIRUN=/soft/mvapich2/1.4-intel-11.1.059/bin/mpiexec

$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   1024    512
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   2048    1024
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   3072    1536
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   4096    2048
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   5120    2560
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   6144    3072
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   7168    3584
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   8192    4096
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   9216    4608
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   10240   5120
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   11264   5632
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   12288   6144
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   13312   6656
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   14336   7168
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   15360   7680
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   16384   8192
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   17408   8704
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   18432   9216
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   19456   9728
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   20480   10240
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   21504   10752
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   22528   11264
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   23552   11776
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   24576   12288
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   25600   12800
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   26624   13312
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   27648   13824
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   28672   14336
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   29696   14848
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   30720   15360
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   31744   15872
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   32768   16384
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   33792   16896
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   34816   17408
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   35840   17920
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   36864   18432
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   37888   18944
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   38912   19456
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   39936   19968
$MPIRUN /homes/jhammond/hpcinchemistrytutorial/cublas_examples/ga_cpu_sgemm.x   40960   20480

