#!/bin/bash

export MPI_HOME=/soft/apps/mpich2-1.2.1
export OMP_NUM_THREADS=4
export KMP_NUM_THREADS=4

$MPI_HOME/bin/mpdboot -n 2 -f $COBALT_NODEFILE
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192 8192
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192 4096
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192 2048
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192 1024
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192  512
$MPI_HOME/bin/mpirun -np 4 ga_gpu_sgemm.x 8192  256
kill -9
