#!/bin/sh
#PBS -N test_driver
#PBS -l nodes=1:ppn=8
#PBS -l walltime=0:29:00
#PBS -j oe
#PBS -q lincoln_debug
#PBS -V

export OMP_NUM_THREADS=8
export KMP_NUM_THREADS=8

echo "Using threaded BLAS"
#/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 1 1 1401 1600 1
#/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 1 1 1601 1800 1
#/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 1 1 1801 2000 1
/u/ac/jhammond/hpcinchemistrytutorial/cublas_examples/test_driver_P.x 1 1 2000 4000 100
